env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  prettier/prettier: [ 2 , {
      "singleQuote": true,
      "trailingComma": "all",
      "printWidth": 120
    }]
